<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.7.9 on win32)" generated="20210112 15:28:37.883" rpa="false">
<suite id="s1" name="Login Suite" source="C:\Users\CTEA\eclipse-workspace\Robot_Framework\Robot_workspace\Robot_Framework\Majento\Login_Suite.robot">
<test id="s1-t1" name="TC1_ValidCredential">
<kw name="Log To Console" library="BuiltIn">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>Hello</arg>
</arguments>
<status status="PASS" starttime="20210112 15:28:37.926" endtime="20210112 15:28:37.927"></status>
</kw>
<status status="PASS" starttime="20210112 15:28:37.925" endtime="20210112 15:28:37.927" critical="yes"></status>
</test>
<status status="PASS" starttime="20210112 15:28:37.886" endtime="20210112 15:28:37.928"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="Login Suite">Login Suite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210112 15:28:37.923" level="ERROR">Error in file 'C:\Users\CTEA\eclipse-workspace\Robot_Framework\Robot_workspace\Robot_Framework\Majento\Login_Suite.robot' on line 2: Importing test library 'DataTime' failed: ModuleNotFoundError: No module named 'DataTime'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\CTEA\eclipse-workspace\Robot_Framework\Robot_workspace\venv\Scripts\robot.exe
  D:\Python\python37.zip
  D:\Python\DLLs
  D:\Python\lib
  D:\Python
  c:\users\ctea\eclipse-workspace\robot_framework\robot_workspace\venv
  c:\users\ctea\eclipse-workspace\robot_framework\robot_workspace\venv\lib\site-packages</msg>
</errors>
</robot>
